### ISSUE TITLE
read-only-mode modifies state

### ISSUE THREAD

**Issue by spinus** [NixOS/nixops#471] opened 2016-07-18 12:16 UTC
```
$ nixops deploy --read-only-mode
m1> EC2 instance was stopped, restarting...
m1> waiting for IP address... [pending] [pending] [pending] [pending] [pending] 
```

I only wanted to check what will be modified.
Would be nice to have something similar to terraform plan, when it generates the actions will be taken, you can review them and then execute modifications on the network.

**Comment by spinus** [comment] 2016-07-18 12:19
Same with destroy, destroy deleted my machine even in read-only-mode :(

**Comment by rbvermaa** [comment] 2016-07-18 12:20
The option is just for Nix evaluations, as described in the --help:
  
      --read-only-mode      run Nix evaluations in read-only mode

**Comment by rbvermaa** [comment] 2016-07-18 12:21
Currently there is no functionality that can generate a full plan of steps that will be executed.

**Comment by rbvermaa** [comment] 2016-07-18 12:22
Closing this as a duplicate of #316

**Closed by rbvermaa** 2016-07-18 12:22 UTC

**Comment by spinus** [comment] 2016-07-18 13:58
@rbvermaa oh, thanks for pointing this out, I was not focused enough. Anyway I think this option is misleading a little bit...
