### ISSUE TITLE
EC2 machine does not get recreated with --allow-recreate

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#902] opened 2018-03-08 09:19 UTC
In the EC2 Console (outside of nixops) I terminated the machine named query. I expected the following command to recreate it, which it does not. 

Executing `nixops deploy  -d mydeployment --include query --allow-recreate`

returns:
```
Traceback (most recent call last):
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/bin/.nixops-wrapped", line 985, in <module>
    args.op()
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/bin/.nixops-wrapped", line 407, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1051, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1040, in run_with_notify
    f()
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1051, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 984, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 957, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/ec2.py", line 954, in create
    instance = self._get_instance()
  File "/nix/store/2w77gs2fky0vl8zlhf1bc4pz6z6d58sh-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/backends/ec2.py", line 306, in _get_instance
    raise EC2InstanceDisappeared("EC2 instance ‘{0}’ disappeared!".format(instance_id))
nixops.backends.ec2.EC2InstanceDisappeared: EC2 instance ‘i-0df87bd64686b874d’ disappeared!
```

**Comment by coretemp** [comment] 2018-03-22 11:30
@rbvermaa Can you give a response to this issue? Not being able to delete a random machine and then have it come back up again after a deploy seems to make nixops completely useless.

**Comment by AmineChikhaoui** [comment] 2018-03-22 11:52
@coretemp doing a `nixops check` should reconcile the nixops state with the outside world, then you could run `nixops deploy --allow-recreate` I think.

**Comment by coretemp** [comment] 2018-03-23 09:10
@AmineChikhaoui `nixops check` returned exit code 16. 
In yellow it showed `proc-sys-fs-binfmt_misc.mount [failed]`. All other output was green. 

Exit code 16 is not documented in `man nixops`.

**Comment by AmineChikhaoui** [comment] 2018-03-23 09:56
Not sure the exit code is relevant to your case, but it did reconcile the state of the nixops internally, the exit code is most likely because one of the machine services is failed namely `proc-sys-fs-binfmt_misc.mount` but that can be ignored I think (we probably need to skip it in the check implementation).

**Comment by coretemp** [comment] 2018-03-26 09:33
@AmineChikhaoui As a user I haven't done anything with `binfmt_misc.mount`, so that just seems a bug too. 

Semantically `--allow-recreate` should imply running `nixops check` if needed automatically. Flags that don't actually do anything are harmful. Either the flag should say "you specified a flag that is not applicable in this context. Perhaps you want to run nixops check" or it should have the above behaviour.

**Comment by peterhoeg** [comment] 2018-10-25 02:12
Duplicate of #418.

Please open a separate issue for the new output and change in behaviour.

**Closed** 2020-04-20 16:15 UTC
