### ISSUE TITLE
nixops deploys wrong schema

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#603] opened 2017-02-10 10:36 UTC
I just provisioned a new machine on Hetzner with nixops. After the initial successful deployment I did another deployment during which I got the following error:

```
$ nixops deploy  -s deployment/state.nixops -d stalling-net --include hermes
building all machine configurations...
hermes..........> copying closure...
hermes..........> error: current Nix store schema is version 10, but I only support 7
```

Note that I'm using `nixos-16.09` and I haven't overridden `nix` with `nixUnstable` or anything. On `hermes` I'm using the following version of the nix tools:

```
$ nix-store --version
nix-store (Nix) 1.11.6
```

The Nix schema on `hermes` is indeed 10 (on my workstation it's 7):

```
$ cat /nix/var/nix/db/schema
10
```

After removing `/nix/var/nix/db/schema` the deployment went successful and the schema was back at 7:   

```
$ cat /nix/var/nix/db/schema
7
```

Any idea what's going on?

**Comment by rbvermaa** [comment] 2017-02-10 10:39
@basvandijk Is this after the initial reboot (so after the bootstrapping of nixos via the rescue system?)

**Comment by rbvermaa** [comment] 2017-02-10 10:39
@aszlig Have you seen this before? 

@basvandijk  I will try to reproduce with 16.09 today.

**Comment by rbvermaa** [comment] 2017-02-10 10:41
@basvandijk Is this with nixops 1.4 btw?

**Comment by aszlig** [comment] 2017-02-10 10:49
I think this should be the issue: https://github.com/NixOS/nixops/blob/c3b164a51fd7e2c97e247552c5c70b08c844bab8/nix/hetzner-bootstrap.nix#L83

**Comment by rbvermaa** [comment] 2017-02-10 10:51
@aszlig So this bootstrap gets built with a different nixpkgs, I guess (from NIX_PATH of the nixops process) ?

**Comment by aszlig** [comment] 2017-02-10 10:52
@rbvermaa: Considering c5c49a18c84e983ba1a0446d2ce294c76ab084c8, is this still the case for Nix 1.11? Because if that's not the case we can just get back to not use `nixUnstable` during bootstrap.

**Comment by rbvermaa** [comment] 2017-02-10 10:53
@aszlig will test that, thanks.

**Comment by basvandijk** [comment] 2017-02-10 13:26
Great, I see you guys already spotted the problem. 

@rbvermaa let me still answer your initial questions:

* I believe I noticed it after the initial reboot when I did a second `nixops deploy`.

* I'm using the default nixops that comes with `nixos-16.09` which is `nixops-1.4`.

**Comment by rbvermaa** [comment] 2017-02-10 14:59
@basvandijk Although I think the solution that aszlig mentions, will fix the issue for you, I haven't been able to reproduce the issue with nixops 1.4 and nixos-16.09 yet. Could you run one more command and post the output:

     $ nix-instantiate --eval-only '<nixpkgs>' -A lib.nixpkgsVersion

Please run this with the same NIX_PATH env variable as your nixops call (note that if you use -I to pass nixops a different nixpkgs, I do *not* need this one)

**Comment by basvandijk** [comment] 2017-02-10 16:01
@rbvermaa the output is `"16.09pre-git"`. Note I'm using the following revision of nixpkgs:

```json
{
  "url": "https://github.com/NixOS/nixpkgs.git",
  "rev": "cd58b22b178cb01e17aeac548279293a847162f9",
  "date": "2017-02-06T20:06:19+01:00",
  "sha256": "0b5z38jm5b58pijjxyhlzisyna3x362rr7ijklnrnkggipxd32sx"
}
```

**Comment by fuzzy-id** [comment] 2017-02-12 15:04
I just ran into this issue, too. I deploy to Hetzner. Initial deployment works. I stumbled over the error pasted by the OP after doing `nixops modify […]` and `nixops deploy […]`.
```
$ nixops --version
NixOps 1.4
$ nix-instantiate --eval-only '<nixpkgs>' -A lib.nixpkgsVersion 
"16.09.1650.d2cd8a0"
```

**Comment by domenkozar** [comment] 2017-02-13 09:21
Sounds like this is fixed in https://github.com/NixOS/nixops/commit/08d5156943c4fbe404d9be9abe39310f3e0c6524

**Comment by domenkozar** [comment] 2017-07-24 12:09
This appears to be fixed as said. Please reopen if issue persits.

**Closed by domenkozar** 2017-07-24 12:09 UTC
Labels: backends/hetzner, bug
