### ISSUE TITLE
nixops ssh is broken on Mac: database disk image is malformed

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#1035] opened 2018-11-01 09:32 UTC
When I try to run 
```
nixops ssh -s state.nixops --deployment d machine -F /dev/null
```

where nixops is the `master` (4d8a49eb632cecf2e522448151a8bd5e68cb2daf) version of nixops on a Mac 10.13.6.

I get

```
Traceback (most recent call last):
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/bin/.nixops-wrapped", line 990, in <module>
    args.op()
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/bin/.nixops-wrapped", line 561, in op_ssh
    allow_ssh_args=True, user=user))
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/lib/python2.7/site-packages/nixops/ssh_util.py", line 280, in run_command
    master = self.get_master(flags, timeout, user)
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/lib/python2.7/site-packages/nixops/ssh_util.py", line 190, in get_master
    if self._host_fun() == "localhost":
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/lib/python2.7/site-packages/nixops/backends/ec2.py", line 172, in get_ssh_name
    if not self.private_ipv4:
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/lib/python2.7/site-packages/nixops/util.py", line 245, in get
    s = self._get_attr(name, default)
  File "/nix/store/9v1hri5laa7dd54lz5k33dnnl5pmrz7r-nixops-1.6.1pre0_abcdef/lib/python2.7/site-packages/nixops/resources/__init__.py", line 91, in _get_attr
    c.execute("select value from ResourceAttrs where machine = ? and name = ?", (self.id, name))
pysqlite2.dbapi2.DatabaseError: database disk image is malformed
```

Using the same nixops state file on Linux with the same `master` version *does* work (it logs me in to the machine via ssh).

**Comment by coretemp** [comment] 2018-11-02 12:16
When running `sqlite3 state.ops` and then typing `PRAGMA integrity_check;`,:
```
*** in database main ***
Page 26: btreeInitPage() returns error code 11
On tree page 9 cell 5: Rowid 38624 out of order
On tree page 25 cell 40: Rowid 40477 out of order
On tree page 25 cell 0: Rowid 39359 out of order
Page 24: btreeInitPage() returns error code 11
Page 28 is never used
Page 32 is never used
Error: database disk image is malformed
```

Doing the same with the exact same file on Linux returns:
```
ok
```

**Comment by coretemp** [comment] 2018-11-02 12:38
When using sqlite3 `3.22.0` inside a Nix based docker image on that Mac returns a similar corruption.

**Comment by wmertens** [comment] 2019-05-07 13:23
This is a duplicate of #1036 I suppose. The error you have can not occur with normal use of sqlite through the client libraries (there's billions of installations that work fine), so you either have a hardware issue, or a macOS filesystem bug (not impossible), or maybe there's something messing with the db files?

**Comment by wmertens** [comment] 2019-05-07 13:24
how are you using the docker image with nixops? SQLite is not happy on networked storage.

**Closed** 2020-04-20 16:16 UTC
