### ISSUE TITLE
libvirt backed is not working when using GUI mode

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixops#422] opened 2016-04-10 11:37 UTC
i'm currently on a fedora box with nix in single user nix setup, and im trying to declare my initial nix system configuration that way 

my basic setup is nix, nixops installed via nix, and then a system declaration for a nixos system to be deployed into libvirt

unfortunately the libvirt daemons run into tonns of permission issues with different image locations

at the moment the only way to seemingly handle that is to use selinux and broad permissions all over the place

and then slowly tracking all the selinux errors

afterwards i still end up with 

```
$ LC_ALL=C nixops deploy
main> starting...
main> error: Failed to create domain from /tmp/nixops-tmpOSUCRG/main-domain.xml
main> error: Interner Fehler: Prozess während der Verbindungsaufnahme zum Monitor beendet :No protocol specified
main> Could not initialize SDL(x11 not available) - exiting
main> 
main> 
error: command ‘['virsh', '-c', 'qemu:///system', 'create', '/tmp/nixops-tmpOSUCRG/main-domain.xml']’ failed on machine ‘main’ (exit code 1)
```

the system spec i try to use is 

```
{}:
{
  main = {
      deployment.targetEnv = "libvirtd";
      deployment.libvirtd.imageDir = "/home/images";
  };
}

```

**Comment by domenkozar** [comment] 2016-05-11 09:10
I think you also need to set `deployment.libvirtd.headless = true;`

**Comment by domenkozar** [comment] 2016-05-12 02:24
Hmm, this is probably broken since X11 security access fix.

**Comment by domenkozar** [comment] 2016-05-12 02:24
@rbvermaa this needs to be fixed before 1.4

**Comment by domenkozar** [comment] 2016-05-12 12:52
```
$ virsh -c qemu:///system create /run/user/499/nixops-tmpFon7Tz/kamdanes-domain.xml
error: Failed to create domain from /run/user/499/nixops-tmpFon7Tz/kamdanes-domain.xml
error: internal error: process exited while connecting to monitor: No protocol specified
Could not initialize SDL(No available video device) - exiting
```

I assume it's XAuthority issue communicating with libvirtd daemon (or the other way around, it doesn't have access to my users XAauthority)

**Comment by domenkozar** [comment] 2016-05-12 12:59
Similar observations: https://bugs.launchpad.net/ubuntu-release-notes/+bug/643583

Workaround is to use `deployment.libvirtd.headless = true;` for now.

**Comment by domenkozar** [comment] 2016-05-12 13:02
Even with `<graphics type="sdl" display=":0.0" xauth="/home/ielectric/.Xauthority"/>` it still won't start, I assume the qemu running doesn't have access to that file.

**Comment by domenkozar** [comment] 2016-05-20 17:12
@rbvermaa I think this is serious enough that it has to be fixed before 1.4

**Comment by rbvermaa** [comment] 2016-05-21 10:45
@domenkozar Did this work previously? Also, any idea how to fix the issue?

**Comment by domenkozar** [comment] 2016-05-21 11:03
@rbvermaa yes. Currently libvirtd backend doesn't work unless you disable GUI.

I'm almost certain https://github.com/NixOS/nixpkgs/commit/659c41a7d59d8354c58dccf5b97637b6a633aed9 "broke" this, but haven't verified.

We need a way to give libvirtd permissions to access X session by the user.

**Comment by rbvermaa** [comment] 2016-05-21 11:06
@domenkozar I don't see how this can be fixed in nixops? Seems more like a system setup issue. We could make the headless setup default.

**Comment by domenkozar** [comment] 2016-05-21 11:15
Workaround would be to make headless default, but that's unfortunate UX problem if we also don't do the same for other backends (VirtualBox).

I'm not sure on what side this should be fixed, but `<graphics>` does support `xauth` parameter in libvirt domain.

**Comment by domenkozar** [comment] 2016-05-25 11:07
I've written most basic documentation for libvirtd and noted this issue: https://github.com/NixOS/nixops/commit/7f3579471f2ea066f6bbf0140f9011d51d763693

**Comment by domenkozar** [comment] 2016-06-04 11:13
What's strange to me is:

```
$ XAUTHORITY=/home/ielectric/.Xauthority qemu-system-x86_64 -display sdl
```

works. But following line in nixops doesn't:

```
            '    <graphics type="sdl" display=":0.0" xauth="/home/ielectric/.Xauthority" />' if not defn.headless else "",
```

But if I change the file for root xauth, it works.

**Comment by domenkozar** [comment] 2016-06-06 10:57
See https://github.com/NixOS/nixops/pull/447

**Comment by johan-boule** [comment] 2016-11-28 01:21
I can confirm all the problems are security ones.

I gave nixops a try with libvirt/qemu/kvm on a Unbuntu 16.04 host, with the nix package manager installed for a single-user (i.e. `/nix/` owned by user 1000, no nix-daemon, no chroot builds).

With the default configuration, it all fails due to nice security features :
1) The default disk image directory, `/var/lib/libvirt/images/`, is accessible only to the root user,
2) Apparmor gets in the way and libvirtd cannot transition to the profiles that where automatically created as `/etc/apparmor.d/libvirt/libvirt-<uuid>`
3) Qemu can't find and/or can't read your X Window cookie, hence non-headless startup is failing.

As a last resort, I temporarily took back control over my machine by joyfully disabling all security, and at least had some fun at the end of the day :)
These are the needed changes to have nixops deploy the VM fine, with a video device enabled, and showing up on your screen :
1) Add an option in your deployment nix file to change the image directory, e.g., `deployment.libvirtd.imageDir = "/tmp";` Also, prevent your disk image file from being chowned so that `nixops destroy` will work: in `/etc/libvirt/qemu.conf` put a line with `dynamic_ownership = 0`
2) Disable Apparmor or SELinux: in `/etc/libvirt/qemu.conf` put a line with `security_driver = "none"`
3) Disable X Window security: `host +`

Of course this is not pretty at all.

**Comment by erowley** [comment] 2017-07-06 04:11
I receive this error simply when starting a VM from nixos-rebuild build-vm over SSH.

**Comment by pjones** [comment] 2017-10-04 22:40
Isn't this issue due to SDL being used as the graphics driver?  When creating libvirt VMs outside of NixOps this is the graphics configuration I use:

```xml
     <graphics type='vnc' autoport='yes' listen='127.0.0.1'>               
       <listen type='address' address='127.0.0.1'/>                                    
     </graphics>                                                                       
```

This setting does not require the GUI to start when running `nixops deploy`.  Instead, you have to manually start a VNC client to connect to the GUI, which avoids any xauth issues.

**Comment by pjones** [comment] 2017-11-02 19:15
Just to follow up, this configuration works:

```Nix
{
      deployment.libvirtd.headless = true;

      deployment.libvirtd.extraDevicesXML = ''
        <graphics type='vnc' port='-1' autoport='yes'/>
      '';
}
```

I think this should be the default.  I'll work up a PR when I get some time.

**Closed** 2017-12-09 15:18 UTC
Labels: backends/libvirtd, bug
